"""Updare tables v0.1.0

Revision ID: 050683b9c219
Revises: 3efcf54e9ebf
Create Date: 2020-08-18 13:53:29.874038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050683b9c219'
down_revision = '3efcf54e9ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_mtm',
    sa.Column('tasks_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tasks_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tasks_id', 'users_id')
    )
    op.add_column('dashboards', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dashboards', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dashboards', type_='foreignkey')
    op.drop_column('dashboards', 'admin_id')
    op.drop_table('tasks_mtm')
    # ### end Alembic commands ###
