"""Updare tables v0.1.2

Revision ID: 086a999050ec
Revises: dc5b4a9729a5
Create Date: 2020-08-18 14:22:22.474697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086a999050ec'
down_revision = 'dc5b4a9729a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'description')
    # ### end Alembic commands ###
