"""Update tables v0.0.2

Revision ID: 3efcf54e9ebf
Revises: dfb381e049e1
Create Date: 2020-08-17 23:50:53.431060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efcf54e9ebf'
down_revision = 'dfb381e049e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dashboards_tasks_key', 'dashboards', type_='unique')
    op.drop_column('dashboards', 'tasks')
    op.add_column('tasks', sa.Column('dashboard_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'dashboards', ['dashboard_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'dashboard_id')
    op.add_column('dashboards', sa.Column('tasks', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint('dashboards_tasks_key', 'dashboards', ['tasks'])
    # ### end Alembic commands ###
