"""Updare tables v0.1.1

Revision ID: dc5b4a9729a5
Revises: 050683b9c219
Create Date: 2020-08-18 14:09:30.071352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5b4a9729a5'
down_revision = '050683b9c219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards_mtm',
    sa.Column('dashboards_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dashboards_id'], ['dashboards.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('dashboards_id', 'users_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboards_mtm')
    # ### end Alembic commands ###
