"""Update tables v0.0.1

Revision ID: dfb381e049e1
Revises: 936b8dff073a
Create Date: 2020-08-17 23:28:52.020895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb381e049e1'
down_revision = '936b8dff073a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('tasks', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'dashboards', ['tasks'])
    op.add_column('tasks', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('description', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'admin_id')
    op.drop_constraint(None, 'dashboards', type_='unique')
    op.drop_column('dashboards', 'tasks')
    # ### end Alembic commands ###
